-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_outputs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid,
  related_entity_type text,
  related_entity_id uuid,
  output_type text NOT NULL CHECK (output_type = ANY (ARRAY['Draft'::text, 'Suggestion'::text, 'Insight'::text, 'Alert'::text, 'Summary'::text, 'Risk Flag'::text])),
  output_category text,
  content text NOT NULL,
  structured_data jsonb DEFAULT '{}'::jsonb,
  model_name text,
  model_version text,
  prompt_template text,
  confidence_score numeric,
  reviewed boolean DEFAULT false,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  accepted boolean DEFAULT false,
  accepted_by uuid,
  accepted_at timestamp with time zone,
  rejection_reason text,
  used_in_entity_type text,
  used_in_entity_id uuid,
  generated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_outputs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_outputs_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT ai_outputs_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT ai_outputs_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.alert_definitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  alert_name text NOT NULL UNIQUE,
  alert_category text NOT NULL CHECK (alert_category = ANY (ARRAY['Deadline'::text, 'Approval Pending'::text, 'Quality Issue'::text, 'Payment'::text, 'Programme Delay'::text, 'Contract Event'::text, 'System'::text])),
  description text,
  trigger_conditions jsonb NOT NULL,
  severity text NOT NULL DEFAULT 'Low'::text CHECK (severity = ANY (ARRAY['Critical'::text, 'High'::text, 'Medium'::text, 'Low'::text, 'Info'::text])),
  notify_email boolean DEFAULT true,
  notify_in_app boolean DEFAULT true,
  notify_sms boolean DEFAULT false,
  recipient_roles ARRAY,
  recipient_users ARRAY,
  escalation_enabled boolean DEFAULT false,
  escalation_after_hours integer,
  escalate_to_roles ARRAY,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alert_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.alert_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  alert_instance_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['Created'::text, 'Acknowledged'::text, 'Resolved'::text, 'Dismissed'::text, 'Escalated'::text, 'Reopened'::text])),
  performed_by uuid,
  action_note text,
  action_timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT alert_history_pkey PRIMARY KEY (id),
  CONSTRAINT alert_history_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.alert_instances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  alert_definition_id uuid NOT NULL,
  contract_id uuid,
  entity_type text,
  entity_id uuid,
  alert_title text NOT NULL,
  alert_message text NOT NULL,
  severity text NOT NULL,
  assigned_to_user_id uuid,
  assigned_to_role text,
  status text DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Acknowledged'::text, 'Resolved'::text, 'Dismissed'::text, 'Escalated'::text])),
  triggered_at timestamp with time zone DEFAULT now(),
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  resolution_note text,
  escalated boolean DEFAULT false,
  escalated_at timestamp with time zone,
  escalated_to_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT alert_instances_pkey PRIMARY KEY (id),
  CONSTRAINT alert_instances_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT alert_instances_assigned_to_user_id_fkey FOREIGN KEY (assigned_to_user_id) REFERENCES auth.users(id),
  CONSTRAINT alert_instances_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES auth.users(id),
  CONSTRAINT alert_instances_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id),
  CONSTRAINT alert_instances_escalated_to_user_id_fkey FOREIGN KEY (escalated_to_user_id) REFERENCES auth.users(id),
  CONSTRAINT alert_instances_alert_definition_id_fkey FOREIGN KEY (alert_definition_id) REFERENCES public.alert_definitions(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['CREATE'::text, 'UPDATE'::text, 'DELETE'::text, 'APPROVE'::text, 'REJECT'::text, 'SUBMIT'::text, 'ACKNOWLEDGE'::text, 'CERTIFY'::text, 'LOCK'::text])),
  performed_by uuid NOT NULL,
  performed_by_name text NOT NULL,
  performed_by_role text,
  old_data jsonb,
  new_data jsonb,
  changed_fields ARRAY,
  change_reason text,
  contract_id uuid,
  ip_address text,
  user_agent text,
  record_hash text,
  audit_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES auth.users(id),
  CONSTRAINT audit_log_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.boq (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  boq_number character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  currency character varying DEFAULT 'MYR'::character varying,
  status character varying DEFAULT 'draft'::character varying,
  total_amount numeric DEFAULT 0.00,
  total_items integer DEFAULT 0,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT boq_pkey PRIMARY KEY (id),
  CONSTRAINT boq_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.boq_item_breakdown (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boq_item_id uuid NOT NULL,
  component_name character varying NOT NULL,
  component_type character varying,
  quantity numeric,
  unit character varying,
  unit_cost numeric,
  total_cost numeric DEFAULT (quantity * unit_cost),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT boq_item_breakdown_pkey PRIMARY KEY (id),
  CONSTRAINT boq_item_breakdown_boq_item_id_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id)
);
CREATE TABLE public.boq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boq_id uuid NOT NULL,
  section_id uuid,
  item_number character varying NOT NULL,
  description text NOT NULL,
  item_type character varying NOT NULL,
  unit character varying NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  unit_rate numeric NOT NULL CHECK (unit_rate >= 0::numeric),
  amount numeric DEFAULT (quantity * unit_rate),
  quantity_done numeric DEFAULT 0.00,
  percentage_complete numeric DEFAULT 0.00 CHECK (percentage_complete >= 0::numeric AND percentage_complete <= 100::numeric),
  specifications text,
  notes text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT boq_items_pkey PRIMARY KEY (id),
  CONSTRAINT boq_items_boq_id_fkey FOREIGN KEY (boq_id) REFERENCES public.boq(id),
  CONSTRAINT boq_items_section_id_fkey FOREIGN KEY (section_id) REFERENCES public.boq_sections(id)
);
CREATE TABLE public.boq_sections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  boq_id uuid NOT NULL,
  section_number character varying NOT NULL,
  title character varying NOT NULL,
  description text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT boq_sections_pkey PRIMARY KEY (id),
  CONSTRAINT boq_sections_boq_id_fkey FOREIGN KEY (boq_id) REFERENCES public.boq(id)
);
CREATE TABLE public.car (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ncr_id uuid NOT NULL,
  car_number text NOT NULL,
  corrective_action_required text NOT NULL,
  assigned_to uuid,
  assigned_by uuid NOT NULL,
  assigned_date timestamp with time zone DEFAULT now(),
  target_completion_date date NOT NULL,
  actual_completion_date date,
  implementation_description text,
  implementation_status text DEFAULT 'Pending'::text CHECK (implementation_status = ANY (ARRAY['Pending'::text, 'In Progress'::text, 'Completed'::text, 'Overdue'::text])),
  verification_required boolean DEFAULT true,
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_remarks text,
  implementation_photos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT car_pkey PRIMARY KEY (id),
  CONSTRAINT car_ncr_id_fkey FOREIGN KEY (ncr_id) REFERENCES public.ncr(id),
  CONSTRAINT car_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.contract_members(id),
  CONSTRAINT car_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id),
  CONSTRAINT car_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id)
);
CREATE TABLE public.claim_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  claim_id uuid NOT NULL,
  boq_item_id uuid NOT NULL,
  quantity_claimed numeric NOT NULL DEFAULT 0 CHECK (quantity_claimed >= 0::numeric),
  cumulative_quantity numeric NOT NULL DEFAULT 0 CHECK (cumulative_quantity >= 0::numeric),
  boq_quantity numeric NOT NULL,
  percentage_complete numeric DEFAULT 0.00 CHECK (percentage_complete >= 0::numeric AND percentage_complete <= 100::numeric),
  unit_rate numeric NOT NULL,
  amount numeric DEFAULT 0.00,
  notes text,
  work_description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT claim_items_pkey PRIMARY KEY (id),
  CONSTRAINT claim_items_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.progress_claims(id),
  CONSTRAINT claim_items_boq_item_id_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id)
);
CREATE TABLE public.contract_baseline_locks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  is_locked boolean NOT NULL DEFAULT true,
  locked_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_by uuid,
  lock_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contract_baseline_locks_pkey PRIMARY KEY (id),
  CONSTRAINT contract_baseline_locks_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_baseline_locks_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_document_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  lifecycle_stage text NOT NULL,
  section_code text NOT NULL,
  section_title text NOT NULL,
  item_code text NOT NULL,
  item_title text NOT NULL,
  description text,
  data_type text NOT NULL DEFAULT 'PDF'::text,
  sequence_no integer NOT NULL DEFAULT 0,
  is_mandatory boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  document_type text DEFAULT 'OTHER'::text,
  custom_document_type text,
  CONSTRAINT contract_document_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contract_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  document_type USER-DEFINED NOT NULL,
  contract_section USER-DEFINED NOT NULL,
  custom_document_type text,
  document_title text NOT NULL,
  document_number text,
  version character varying NOT NULL DEFAULT '1.0'::character varying,
  revision_number integer NOT NULL DEFAULT 1,
  issue_date date,
  issuer text,
  issuer_user_id uuid,
  recipient text,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint,
  file_hash text,
  mime_type text DEFAULT 'application/pdf'::text,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::document_status,
  is_current boolean NOT NULL DEFAULT true,
  superseded_by uuid,
  supersedes uuid,
  is_locked boolean NOT NULL DEFAULT false,
  locked_at timestamp with time zone,
  locked_by uuid,
  lock_reason text,
  expiry_date date,
  expiry_alert_days_before integer DEFAULT 30,
  expiry_alert_sent boolean DEFAULT false,
  description text,
  remarks text,
  tags ARRAY,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  template_id uuid,
  storage_path text,
  CONSTRAINT contract_documents_pkey PRIMARY KEY (id),
  CONSTRAINT contract_documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.contract_document_templates(id),
  CONSTRAINT contract_documents_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_documents_issuer_user_id_fkey FOREIGN KEY (issuer_user_id) REFERENCES auth.users(id),
  CONSTRAINT contract_documents_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES public.contract_documents(id),
  CONSTRAINT contract_documents_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES public.contract_documents(id),
  CONSTRAINT contract_documents_locked_by_fkey FOREIGN KEY (locked_by) REFERENCES auth.users(id),
  CONSTRAINT contract_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid,
  member_role text NOT NULL CHECK (member_role = ANY (ARRAY['owner'::text, 'admin'::text, 'editor'::text, 'viewer'::text, 'submitter'::text, 'reviewer'::text, 'approver'::text, 'auditor'::text, 'readonly'::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  invitation_status text DEFAULT 'active'::text CHECK (invitation_status = ANY (ARRAY['pending'::text, 'active'::text, 'removed'::text])),
  trade_scope text,
  created_at timestamp with time zone DEFAULT now(),
  removed_at timestamp with time zone,
  removed_by uuid,
  CONSTRAINT contract_members_pkey PRIMARY KEY (id),
  CONSTRAINT contract_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contract_members_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_members_removed_by_fkey FOREIGN KEY (removed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_milestones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  milestone_type text NOT NULL CHECK (milestone_type = ANY (ARRAY['CPC'::text, 'WC'::text, 'DLP_Start'::text, 'DLP_End'::text, 'Final_Account'::text, 'Custom'::text])),
  milestone_name text NOT NULL,
  description text,
  planned_date date,
  actual_date date,
  certified_date date,
  certificate_number text,
  certified_by text,
  certified_by_user_id uuid,
  status text DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Pending'::text, 'In Progress'::text, 'Submitted'::text, 'Certified'::text, 'Completed'::text])),
  certificate_url text,
  supporting_documents jsonb DEFAULT '[]'::jsonb,
  outstanding_defects_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT contract_milestones_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_milestones_certified_by_user_id_fkey FOREIGN KEY (certified_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.contract_required_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  template_id uuid NOT NULL,
  is_required boolean DEFAULT true,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contract_required_documents_pkey PRIMARY KEY (id),
  CONSTRAINT contract_required_documents_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT contract_required_documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.contract_document_templates(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_number text NOT NULL UNIQUE,
  project_name text NOT NULL,
  location text NOT NULL,
  contract_type text NOT NULL CHECK (contract_type = ANY (ARRAY['PWD_203A'::text, 'PAM_2018'::text, 'IEM'::text, 'CIDB'::text, 'JKR_DB'::text])),
  contract_value numeric NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  contract_duration_days integer NOT NULL,
  client_name text NOT NULL,
  consultant_name text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'completed'::text, 'suspended'::text])),
  description text,
  organization_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contracts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delay_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  event_number text NOT NULL,
  event_title text NOT NULL,
  event_description text NOT NULL,
  cause_category text NOT NULL CHECK (cause_category = ANY (ARRAY['Weather'::text, 'Variation Order'::text, 'Late Instruction'::text, 'Material Delay'::text, 'Labour Issue'::text, 'Access Issue'::text, 'Design Issue'::text, 'Client Delay'::text, 'Force Majeure'::text, 'Other'::text])),
  cause_detail text,
  event_start_date date NOT NULL,
  event_end_date date,
  total_days_affected integer,
  linked_programme_items jsonb DEFAULT '[]'::jsonb,
  critical_path_impact boolean DEFAULT false,
  estimated_delay_days integer,
  linked_diary_ids jsonb DEFAULT '[]'::jsonb,
  linked_site_instruction_id uuid,
  linked_variation_order_id uuid,
  weather_evidence jsonb DEFAULT '[]'::jsonb,
  contractor_notified text,
  notification_date date,
  notification_reference text,
  eot_claimed boolean DEFAULT false,
  linked_eot_claim_id uuid,
  status text DEFAULT 'Open'::text CHECK (status = ANY (ARRAY['Open'::text, 'Under Review'::text, 'Accepted'::text, 'Rejected'::text, 'Closed'::text])),
  recorded_by uuid NOT NULL,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_comments text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT delay_events_pkey PRIMARY KEY (id),
  CONSTRAINT delay_events_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT delay_events_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id),
  CONSTRAINT delay_events_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.diary_boq_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diary_id uuid NOT NULL,
  boq_item_id uuid NOT NULL,
  quantity_completed numeric,
  unit text,
  previous_cumulative numeric DEFAULT 0,
  new_cumulative numeric NOT NULL DEFAULT 0,
  total_quantity numeric,
  percent_complete numeric CHECK (percent_complete >= 0::numeric AND percent_complete <= 100::numeric),
  activity_title text NOT NULL,
  work_description text,
  location text,
  quality_verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  included_in_claim_id uuid,
  claim_reference text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  diary_work_activity_id uuid,
  CONSTRAINT diary_boq_links_pkey PRIMARY KEY (id),
  CONSTRAINT diary_boq_links_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT diary_boq_links_boq_item_id_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT diary_boq_links_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id),
  CONSTRAINT diary_boq_links_included_in_claim_id_fkey FOREIGN KEY (included_in_claim_id) REFERENCES public.progress_claims(id),
  CONSTRAINT diary_boq_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT diary_boq_links_diary_work_activity_id_fkey FOREIGN KEY (diary_work_activity_id) REFERENCES public.diary_work_activities(id)
);
CREATE TABLE public.diary_observations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diary_id uuid,
  contract_id uuid,
  title text NOT NULL,
  description text,
  category text CHECK (category = ANY (ARRAY['general'::text, 'quality'::text, 'commercial'::text, 'technical'::text])),
  severity text DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  linked_to jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  reported_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diary_observations_pkey PRIMARY KEY (id),
  CONSTRAINT diary_observations_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT diary_observations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT diary_observations_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.diary_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  diary_id uuid NOT NULL,
  storage_path text NOT NULL,
  file_name text NOT NULL,
  file_size integer NOT NULL,
  mime_type text NOT NULL,
  caption text,
  display_order integer DEFAULT 0,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  weather_observation_id uuid,
  CONSTRAINT diary_photos_pkey PRIMARY KEY (id),
  CONSTRAINT diary_photos_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT diary_photos_weather_observation_id_fkey FOREIGN KEY (weather_observation_id) REFERENCES public.weather_observations(id)
);
CREATE TABLE public.diary_programme_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diary_id uuid NOT NULL,
  programme_item_id uuid NOT NULL,
  progress_update numeric CHECK (progress_update >= 0::numeric AND progress_update <= 100::numeric),
  previous_progress numeric,
  new_progress numeric,
  activity_title text NOT NULL,
  work_description text,
  quantity_completed numeric,
  unit text,
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'delayed'::text, 'on_hold'::text])),
  has_issues boolean DEFAULT false,
  issue_description text,
  delay_days integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  boq_item_id uuid,
  diary_boq_link_id uuid,
  diary_work_activity_id uuid,
  allocation_percent numeric CHECK (allocation_percent >= 0::numeric AND allocation_percent <= 100::numeric),
  CONSTRAINT diary_programme_links_pkey PRIMARY KEY (id),
  CONSTRAINT diary_programme_links_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT diary_programme_links_programme_item_id_fkey FOREIGN KEY (programme_item_id) REFERENCES public.programme_items(id),
  CONSTRAINT diary_programme_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT dpl_boq_item_id_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT dpl_diary_boq_link_id_fkey FOREIGN KEY (diary_boq_link_id) REFERENCES public.diary_boq_links(id),
  CONSTRAINT dpl_diary_work_activity_id_fkey FOREIGN KEY (diary_work_activity_id) REFERENCES public.diary_work_activities(id)
);
CREATE TABLE public.diary_work_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diary_id uuid NOT NULL,
  contract_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  quantity_completed numeric DEFAULT 0,
  unit text,
  percent_complete integer DEFAULT 0 CHECK (percent_complete >= 0 AND percent_complete <= 100),
  status text DEFAULT 'in_progress'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'completed'::text, 'on_hold'::text])),
  notes text,
  requires_inspection boolean DEFAULT false,
  inspection_type text,
  requires_test boolean DEFAULT false,
  test_type text,
  programme_item_id uuid,
  programme_wbs_code text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT diary_work_activities_pkey PRIMARY KEY (id),
  CONSTRAINT diary_work_activities_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT diary_work_activities_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT diary_work_activities_programme_item_id_fkey FOREIGN KEY (programme_item_id) REFERENCES public.programme_items(id),
  CONSTRAINT diary_work_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.document_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL,
  version character varying NOT NULL,
  revision_number integer NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_size bigint,
  file_hash text,
  mime_type text DEFAULT 'application/pdf'::text,
  change_reason text,
  change_summary text,
  changed_from_version character varying,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  storage_path text,
  CONSTRAINT document_versions_pkey PRIMARY KEY (id),
  CONSTRAINT document_versions_uploaded_by_user_profiles_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id),
  CONSTRAINT document_versions_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.contract_documents(id),
  CONSTRAINT document_versions_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.eot_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  eot_claim_number text NOT NULL,
  claim_title text NOT NULL,
  claim_description text,
  claim_period_start date NOT NULL,
  claim_period_end date NOT NULL,
  extension_days_requested integer NOT NULL,
  justification text NOT NULL,
  linked_delay_event_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  programme_analysis_summary text,
  critical_path_analysis text,
  baseline_programme_version integer,
  revised_programme_version integer,
  submitted_by uuid NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  submission_method text,
  submission_reference text,
  status text DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Submitted'::text, 'Under Review'::text, 'Additional Info Required'::text, 'Approved'::text, 'Partially Approved'::text, 'Rejected'::text])),
  reviewed_by text,
  reviewed_by_user_id uuid,
  reviewed_at timestamp with time zone,
  review_comments text,
  extension_days_approved integer,
  approval_conditions text,
  approved_by text,
  approved_at timestamp with time zone,
  original_completion_date date,
  revised_completion_date date,
  supporting_documents jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT eot_claims_pkey PRIMARY KEY (id),
  CONSTRAINT eot_claims_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT eot_claims_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id),
  CONSTRAINT eot_claims_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.event_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_category text NOT NULL CHECK (event_category = ANY (ARRAY['User Action'::text, 'System Action'::text, 'Workflow Transition'::text, 'Integration'::text, 'Security'::text, 'Performance'::text])),
  event_type text NOT NULL,
  entity_type text,
  entity_id uuid,
  actor_id uuid,
  actor_name text,
  actor_role text,
  event_description text,
  event_data jsonb DEFAULT '{}'::jsonb,
  contract_id uuid,
  session_id text,
  ip_address text,
  user_agent text,
  event_timestamp timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_log_pkey PRIMARY KEY (id),
  CONSTRAINT event_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id),
  CONSTRAINT event_log_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.incidents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  incident_number text NOT NULL,
  incident_type text NOT NULL CHECK (incident_type = ANY (ARRAY['Fatality'::text, 'Lost Time Injury'::text, 'Medical Treatment'::text, 'First Aid'::text, 'Property Damage'::text, 'Near Miss'::text])),
  incident_date timestamp with time zone NOT NULL,
  location text NOT NULL,
  incident_description text NOT NULL,
  cause_analysis text,
  injured_persons jsonb DEFAULT '[]'::jsonb,
  witnesses jsonb DEFAULT '[]'::jsonb,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['Fatal'::text, 'Major'::text, 'Minor'::text, 'None'::text])),
  work_days_lost integer DEFAULT 0,
  reported_by uuid NOT NULL,
  reported_to_authorities boolean DEFAULT false,
  authority_report_reference text,
  investigation_required boolean DEFAULT true,
  investigated_by text,
  investigation_report text,
  root_cause text,
  corrective_actions_taken text,
  preventive_measures text,
  status text DEFAULT 'Reported'::text CHECK (status = ANY (ARRAY['Reported'::text, 'Under Investigation'::text, 'Investigation Complete'::text, 'Actions Implemented'::text, 'Closed'::text])),
  photos jsonb DEFAULT '[]'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES auth.users(id)
);
CREATE TABLE public.inspection_test_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  diary_id uuid,
  contract_id uuid,
  request_type text NOT NULL CHECK (request_type = ANY (ARRAY['inspection'::text, 'test'::text])),
  activity_title text,
  inspection_type text,
  test_type text,
  requested_date date NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'completed'::text, 'rejected'::text])),
  notes text,
  requested_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inspection_test_requests_pkey PRIMARY KEY (id),
  CONSTRAINT inspection_test_requests_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT inspection_test_requests_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT inspection_test_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.inspections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  inspection_number text NOT NULL,
  inspection_type text NOT NULL CHECK (inspection_type = ANY (ARRAY['RFI'::text, 'Hold Point'::text, 'Witness Point'::text, 'Routine'::text, 'Final'::text])),
  inspection_category text,
  location text NOT NULL,
  work_description text NOT NULL,
  specifications_reference text,
  linked_diary_id uuid,
  linked_programme_item_id uuid,
  linked_boq_item_id uuid,
  requested_by uuid NOT NULL,
  requested_date timestamp with time zone DEFAULT now(),
  requested_inspection_date date,
  inspected_by text,
  inspected_by_user_id uuid,
  inspection_date timestamp with time zone,
  status text DEFAULT 'Requested'::text CHECK (status = ANY (ARRAY['Requested'::text, 'Scheduled'::text, 'Conducted'::text, 'Approved'::text, 'Rejected'::text, 'Conditional Approval'::text, 'Cancelled'::text])),
  result text CHECK (result = ANY (ARRAY['Pass'::text, 'Fail'::text, 'Conditional'::text, 'N/A'::text])),
  comments text,
  defects_noted text,
  approved_by text,
  approved_by_user_id uuid,
  approved_at timestamp with time zone,
  photos_count integer DEFAULT 0,
  documents_attached jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inspections_pkey PRIMARY KEY (id),
  CONSTRAINT inspections_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT inspections_linked_diary_id_fkey FOREIGN KEY (linked_diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT inspections_linked_programme_item_id_fkey FOREIGN KEY (linked_programme_item_id) REFERENCES public.programme_items(id),
  CONSTRAINT inspections_linked_boq_item_id_fkey FOREIGN KEY (linked_boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT inspections_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id),
  CONSTRAINT inspections_inspected_by_user_id_fkey FOREIGN KEY (inspected_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT inspections_approved_by_user_id_fkey FOREIGN KEY (approved_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.insurance_policies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  policy_type text NOT NULL CHECK (policy_type = ANY (ARRAY['CAR'::text, 'EAR'::text, 'Public Liability'::text, 'Professional Indemnity'::text, 'Workmen Compensation'::text, 'Other'::text])),
  policy_number text NOT NULL,
  insurer_name text NOT NULL,
  coverage_amount numeric NOT NULL,
  currency text DEFAULT 'MYR'::text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean DEFAULT true,
  premium_amount numeric,
  policy_document_url text,
  renewed_policy_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT insurance_policies_pkey PRIMARY KEY (id),
  CONSTRAINT insurance_policies_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT insurance_policies_renewed_policy_id_fkey FOREIGN KEY (renewed_policy_id) REFERENCES public.insurance_policies(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  token text NOT NULL UNIQUE,
  full_name text NOT NULL,
  position text NOT NULL,
  phone text,
  organization_id uuid NOT NULL,
  organization_name text NOT NULL,
  company_type text NOT NULL CHECK (company_type = ANY (ARRAY['main_contractor'::text, 'subcontractor'::text, 'consultant'::text, 'supplier'::text])),
  user_role text NOT NULL CHECK (user_role = ANY (ARRAY['owner'::text, 'admin'::text, 'editor'::text, 'submitter'::text, 'reviewer'::text, 'approver'::text, 'auditor'::text, 'readonly'::text])),
  cidb_registration text,
  ssm_registration text,
  invited_by uuid NOT NULL,
  contract_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'cancelled'::text])),
  invited_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT invitations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.member_activity_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_id uuid NOT NULL,
  action_type text NOT NULL,
  action_by uuid NOT NULL,
  old_value text,
  new_value text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT member_activity_log_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.contract_members(id),
  CONSTRAINT member_activity_log_action_by_fkey FOREIGN KEY (action_by) REFERENCES auth.users(id)
);
CREATE TABLE public.ncr (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  ncr_number text NOT NULL,
  ncr_title text NOT NULL,
  non_conformance_description text NOT NULL,
  location text NOT NULL,
  discovered_date date NOT NULL,
  severity text NOT NULL DEFAULT 'Minor'::text CHECK (severity = ANY (ARRAY['Critical'::text, 'Major'::text, 'Minor'::text])),
  linked_diary_id uuid,
  linked_inspection_id uuid,
  linked_programme_item_id uuid,
  raised_by uuid NOT NULL,
  raised_against text,
  responsible_party uuid,
  status text DEFAULT 'Issued'::text CHECK (status = ANY (ARRAY['Issued'::text, 'CAR Assigned'::text, 'Under Rectification'::text, 'Pending Verification'::text, 'Verified'::text, 'Closed'::text, 'Rejected'::text])),
  rectification_deadline date,
  verified_by uuid,
  verified_at timestamp with time zone,
  closed_by uuid,
  closed_at timestamp with time zone,
  closure_remarks text,
  photos_count integer DEFAULT 0,
  before_photos jsonb DEFAULT '[]'::jsonb,
  after_photos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ncr_pkey PRIMARY KEY (id),
  CONSTRAINT ncr_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT ncr_linked_diary_id_fkey FOREIGN KEY (linked_diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT ncr_linked_inspection_id_fkey FOREIGN KEY (linked_inspection_id) REFERENCES public.inspections(id),
  CONSTRAINT ncr_linked_programme_item_id_fkey FOREIGN KEY (linked_programme_item_id) REFERENCES public.programme_items(id),
  CONSTRAINT ncr_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES auth.users(id),
  CONSTRAINT ncr_responsible_party_fkey FOREIGN KEY (responsible_party) REFERENCES public.contract_members(id),
  CONSTRAINT ncr_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id),
  CONSTRAINT ncr_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  registration_number text,
  cidb_registration text,
  cidb_grade text CHECK (cidb_grade = ANY (ARRAY['G1'::text, 'G2'::text, 'G3'::text, 'G4'::text, 'G5'::text, 'G6'::text, 'G7'::text])),
  organization_type text NOT NULL CHECK (organization_type = ANY (ARRAY['main_contractor'::text, 'subcontractor'::text, 'consultant'::text, 'supplier'::text])),
  address text,
  phone text,
  email text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.performance_bonds (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  bond_type text NOT NULL CHECK (bond_type = ANY (ARRAY['Performance Bond'::text, 'Advance Payment Bond'::text, 'Retention Bond'::text, 'Maintenance Bond'::text])),
  bond_number text NOT NULL,
  bond_amount numeric NOT NULL,
  currency text DEFAULT 'MYR'::text,
  issuer_name text NOT NULL,
  issuer_contact text,
  issue_date date NOT NULL,
  expiry_date date NOT NULL,
  is_active boolean DEFAULT true,
  bond_document_url text,
  renewed_bond_id uuid,
  released_date date,
  release_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT performance_bonds_pkey PRIMARY KEY (id),
  CONSTRAINT performance_bonds_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT performance_bonds_renewed_bond_id_fkey FOREIGN KEY (renewed_bond_id) REFERENCES public.performance_bonds(id)
);
CREATE TABLE public.programme_boq_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  programme_item_id uuid NOT NULL,
  boq_item_id uuid NOT NULL,
  link_type text DEFAULT 'primary'::text,
  weight numeric,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT programme_boq_links_pkey PRIMARY KEY (id),
  CONSTRAINT programme_boq_links_programme_item_fkey FOREIGN KEY (programme_item_id) REFERENCES public.programme_items(id),
  CONSTRAINT programme_boq_links_boq_item_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT programme_boq_links_contract_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.programme_calendars (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  calendar_name text NOT NULL,
  working_days jsonb DEFAULT '{"friday": true, "monday": true, "sunday": false, "tuesday": true, "saturday": false, "thursday": true, "wednesday": true}'::jsonb,
  work_hours_per_day numeric DEFAULT 8.00,
  holidays jsonb DEFAULT '[]'::jsonb,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT programme_calendars_pkey PRIMARY KEY (id),
  CONSTRAINT programme_calendars_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);
CREATE TABLE public.programme_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  wbs_code text NOT NULL,
  description text NOT NULL,
  activity_type text DEFAULT 'Task'::text CHECK (activity_type = ANY (ARRAY['Task'::text, 'Milestone'::text, 'Summary'::text])),
  planned_start date NOT NULL,
  planned_finish date NOT NULL,
  duration_days integer NOT NULL,
  actual_start date,
  actual_finish date,
  actual_duration_days integer,
  percent_complete numeric DEFAULT 0 CHECK (percent_complete >= 0::numeric AND percent_complete <= 100::numeric),
  parent_id uuid,
  level integer DEFAULT 1 CHECK (level >= 1 AND level <= 10),
  sort_order integer DEFAULT 0,
  calendar_id uuid,
  resource_name text,
  linked_boq_item_id uuid,
  programme_version integer NOT NULL DEFAULT 1,
  is_baseline boolean DEFAULT false,
  is_current boolean DEFAULT true,
  status text DEFAULT 'Not Started'::text CHECK (status = ANY (ARRAY['Not Started'::text, 'In Progress'::text, 'Completed'::text, 'Delayed'::text, 'On Hold'::text])),
  is_critical boolean DEFAULT false,
  total_float_days integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT programme_items_pkey PRIMARY KEY (id),
  CONSTRAINT programme_items_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT programme_items_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.programme_items(id),
  CONSTRAINT programme_items_linked_boq_item_id_fkey FOREIGN KEY (linked_boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT programme_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.programme_links (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  predecessor_id uuid NOT NULL,
  successor_id uuid NOT NULL,
  link_type text NOT NULL DEFAULT 'FS'::text CHECK (link_type = ANY (ARRAY['FS'::text, 'SS'::text, 'FF'::text, 'SF'::text])),
  lag_days integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT programme_links_pkey PRIMARY KEY (id),
  CONSTRAINT programme_links_predecessor_id_fkey FOREIGN KEY (predecessor_id) REFERENCES public.programme_items(id),
  CONSTRAINT programme_links_successor_id_fkey FOREIGN KEY (successor_id) REFERENCES public.programme_items(id)
);
CREATE TABLE public.programme_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  version_number integer NOT NULL,
  version_name text NOT NULL,
  version_type text NOT NULL CHECK (version_type = ANY (ARRAY['Baseline'::text, 'Revision'::text, 'As-Built'::text, 'Claim Support'::text])),
  is_approved boolean DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  imported_from text,
  import_file_name text,
  description text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT programme_versions_pkey PRIMARY KEY (id),
  CONSTRAINT programme_versions_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT programme_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT programme_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.progress_claims (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  created_by uuid NOT NULL,
  approved_by uuid,
  claim_number integer NOT NULL,
  claim_title text,
  claim_period_from date NOT NULL,
  claim_period_to date NOT NULL,
  submission_date date DEFAULT CURRENT_DATE,
  payment_due_date date,
  approved_date date,
  payment_date date,
  claim_amount numeric DEFAULT 0.00,
  retention_percentage numeric DEFAULT 5.00 CHECK (retention_percentage >= 0::numeric AND retention_percentage <= 100::numeric),
  retention_amount numeric DEFAULT 0.00,
  net_claim_amount numeric DEFAULT 0.00,
  cumulative_claimed numeric DEFAULT 0.00,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'rejected'::text, 'paid'::text])),
  notes text,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT progress_claims_pkey PRIMARY KEY (id),
  CONSTRAINT progress_claims_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT progress_claims_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT progress_claims_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.report_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['Daily'::text, 'Weekly'::text, 'Monthly'::text, 'Custom'::text, 'Claim Support'::text, 'Close-Out'::text])),
  report_title text NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  period_label text,
  report_data jsonb NOT NULL,
  report_summary text,
  generated_by uuid NOT NULL,
  generated_at timestamp with time zone DEFAULT now(),
  generation_method text,
  status text DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Submitted'::text, 'Reviewed'::text, 'Approved'::text, 'Issued'::text, 'Archived'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_comments text,
  version_number integer DEFAULT 1,
  supersedes_snapshot_id uuid,
  pdf_url text,
  excel_url text,
  is_locked boolean DEFAULT false,
  locked_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT report_snapshots_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT report_snapshots_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id),
  CONSTRAINT report_snapshots_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT report_snapshots_supersedes_snapshot_id_fkey FOREIGN KEY (supersedes_snapshot_id) REFERENCES public.report_snapshots(id)
);
CREATE TABLE public.report_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  report_snapshot_id uuid NOT NULL,
  version_number integer NOT NULL,
  changes_description text,
  changed_by uuid NOT NULL,
  version_data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_versions_pkey PRIMARY KEY (id),
  CONSTRAINT report_versions_report_snapshot_id_fkey FOREIGN KEY (report_snapshot_id) REFERENCES public.report_snapshots(id),
  CONSTRAINT report_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.safety_observations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  observation_number text NOT NULL,
  observation_type text NOT NULL CHECK (observation_type = ANY (ARRAY['Hazard'::text, 'Near Miss'::text, 'Unsafe Act'::text, 'Unsafe Condition'::text, 'Good Practice'::text])),
  observation_description text NOT NULL,
  location text NOT NULL,
  observed_date date NOT NULL,
  observed_by uuid NOT NULL,
  observer_name text,
  risk_level text CHECK (risk_level = ANY (ARRAY['Critical'::text, 'High'::text, 'Medium'::text, 'Low'::text])),
  immediate_action_taken text,
  corrective_action_required boolean DEFAULT false,
  corrective_action_description text,
  assigned_to uuid,
  target_completion_date date,
  actual_completion_date date,
  status text DEFAULT 'Open'::text CHECK (status = ANY (ARRAY['Open'::text, 'In Progress'::text, 'Completed'::text, 'Closed'::text])),
  photos jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT safety_observations_pkey PRIMARY KEY (id),
  CONSTRAINT safety_observations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT safety_observations_observed_by_fkey FOREIGN KEY (observed_by) REFERENCES auth.users(id),
  CONSTRAINT safety_observations_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.contract_members(id)
);
CREATE TABLE public.site_instructions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  instruction_number text NOT NULL,
  instruction_type text NOT NULL CHECK (instruction_type = ANY (ARRAY['Site Instruction'::text, 'Architect Instruction'::text, 'Engineer Instruction'::text, 'Clarification'::text, 'Direction'::text])),
  subject text NOT NULL,
  instruction_detail text NOT NULL,
  issued_by text NOT NULL,
  issued_by_user_id uuid,
  issue_date date NOT NULL,
  directed_to text NOT NULL,
  potential_time_impact boolean DEFAULT false,
  potential_cost_impact boolean DEFAULT false,
  linked_variation_order_id uuid,
  linked_delay_event_id uuid,
  linked_programme_items jsonb DEFAULT '[]'::jsonb,
  response_required boolean DEFAULT false,
  response_deadline date,
  contractor_response text,
  responded_at timestamp with time zone,
  status text DEFAULT 'Issued'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Issued'::text, 'Acknowledged'::text, 'Under Action'::text, 'Completed'::text, 'Closed'::text])),
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  attachment_urls jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_instructions_pkey PRIMARY KEY (id),
  CONSTRAINT site_instructions_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT site_instructions_issued_by_user_id_fkey FOREIGN KEY (issued_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT site_instructions_linked_variation_order_id_fkey FOREIGN KEY (linked_variation_order_id) REFERENCES public.variation_orders(id),
  CONSTRAINT site_instructions_linked_delay_event_id_fkey FOREIGN KEY (linked_delay_event_id) REFERENCES public.delay_events(id),
  CONSTRAINT site_instructions_acknowledged_by_fkey FOREIGN KEY (acknowledged_by) REFERENCES auth.users(id)
);
CREATE TABLE public.test_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  test_number text NOT NULL,
  test_type text NOT NULL CHECK (test_type = ANY (ARRAY['Concrete Cube'::text, 'Soil Compaction'::text, 'Rebar'::text, 'Concrete Slump'::text, 'Steel'::text, 'Other'::text])),
  test_standard text,
  sample_location text NOT NULL,
  sample_date date NOT NULL,
  sample_id text,
  tested_by text,
  test_date date,
  test_result text,
  result_value numeric,
  result_unit text,
  pass_fail text CHECK (pass_fail = ANY (ARRAY['Pass'::text, 'Fail'::text, 'Pending'::text, 'N/A'::text])),
  required_value numeric,
  linked_diary_id uuid,
  linked_inspection_id uuid,
  linked_programme_item_id uuid,
  certificate_number text,
  certificate_file_url text,
  remarks text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT test_records_pkey PRIMARY KEY (id),
  CONSTRAINT test_records_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT test_records_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT test_records_linked_diary_id_fkey FOREIGN KEY (linked_diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT test_records_linked_inspection_id_fkey FOREIGN KEY (linked_inspection_id) REFERENCES public.inspections(id),
  CONSTRAINT test_records_linked_programme_item_id_fkey FOREIGN KEY (linked_programme_item_id) REFERENCES public.programme_items(id)
);
CREATE TABLE public.toolbox_meetings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  meeting_number text NOT NULL,
  meeting_date date NOT NULL,
  meeting_time time without time zone,
  location text,
  topics ARRAY NOT NULL,
  discussion_notes text,
  attendees jsonb DEFAULT '[]'::jsonb,
  total_attendees integer DEFAULT 0,
  conducted_by uuid,
  conductor_name text NOT NULL,
  attendance_sheet_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toolbox_meetings_pkey PRIMARY KEY (id),
  CONSTRAINT toolbox_meetings_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT toolbox_meetings_conducted_by_fkey FOREIGN KEY (conducted_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['main_contractor'::text, 'subcontractor'::text, 'consultant'::text, 'supplier'::text])),
  organization_id uuid,
  organization_name text,
  phone text,
  position text,
  cidb_registration text,
  ssm_registration text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_role text NOT NULL DEFAULT 'editor'::text CHECK (user_role = ANY (ARRAY['owner'::text, 'admin'::text, 'editor'::text, 'viewer'::text, 'submitter'::text, 'reviewer'::text, 'approver'::text, 'auditor'::text, 'readonly'::text])),
  email text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.variation_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  vo_number text NOT NULL,
  vo_title text NOT NULL,
  vo_description text NOT NULL,
  instructed_by text NOT NULL,
  instruction_date date NOT NULL,
  instruction_reference text,
  scope_change_description text NOT NULL,
  reason_for_variation text,
  programme_impact text CHECK (programme_impact = ANY (ARRAY['None'::text, 'Minor'::text, 'Significant'::text, 'Critical'::text])),
  estimated_delay_days integer DEFAULT 0,
  linked_programme_items jsonb DEFAULT '[]'::jsonb,
  vo_type text CHECK (vo_type = ANY (ARRAY['Addition'::text, 'Omission'::text, 'Substitution'::text, 'Daywork'::text])),
  estimated_value numeric,
  currency text DEFAULT 'MYR'::text,
  affected_boq_items jsonb DEFAULT '[]'::jsonb,
  new_boq_items_created jsonb DEFAULT '[]'::jsonb,
  valuation_status text DEFAULT 'Pending'::text CHECK (valuation_status = ANY (ARRAY['Pending'::text, 'Quoted'::text, 'Under Review'::text, 'Agreed'::text, 'Disputed'::text])),
  contractor_quoted_value numeric,
  engineer_valued_amount numeric,
  agreed_value numeric,
  status text DEFAULT 'Instructed'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Instructed'::text, 'Quoted'::text, 'Approved'::text, 'Work In Progress'::text, 'Completed'::text, 'Valued'::text, 'Certified'::text, 'Disputed'::text])),
  approved_by text,
  approved_at timestamp with time zone,
  included_in_claim_id uuid,
  payment_status text CHECK (payment_status = ANY (ARRAY['Pending'::text, 'Included in Claim'::text, 'Certified'::text, 'Paid'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT variation_orders_pkey PRIMARY KEY (id),
  CONSTRAINT variation_orders_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT variation_orders_included_in_claim_id_fkey FOREIGN KEY (included_in_claim_id) REFERENCES public.progress_claims(id),
  CONSTRAINT variation_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.weather_observations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  contract_id uuid NOT NULL,
  diary_id uuid NOT NULL,
  observation_time time without time zone NOT NULL,
  weather_condition text NOT NULL CHECK (weather_condition = ANY (ARRAY['sunny'::text, 'cloudy'::text, 'partly_cloudy'::text, 'overcast'::text, 'light_rain'::text, 'heavy_rain'::text, 'drizzle'::text, 'thunderstorm'::text, 'lightning'::text, 'strong_wind'::text, 'haze'::text, 'fog'::text])),
  temperature numeric CHECK (temperature >= 0::numeric AND temperature <= 50::numeric),
  humidity numeric CHECK (humidity >= 0::numeric AND humidity <= 100::numeric),
  rainfall_mm numeric DEFAULT 0 CHECK (rainfall_mm >= 0::numeric),
  wind_speed_kmh numeric CHECK (wind_speed_kmh >= 0::numeric AND wind_speed_kmh <= 200::numeric),
  work_stoppage boolean DEFAULT false,
  work_stoppage_duration_minutes integer,
  affected_activities ARRAY,
  remarks text,
  photo_urls jsonb DEFAULT '[]'::jsonb,
  recorded_by uuid,
  recorded_by_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weather_observations_pkey PRIMARY KEY (id),
  CONSTRAINT weather_observations_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id),
  CONSTRAINT weather_observations_diary_id_fkey FOREIGN KEY (diary_id) REFERENCES public.work_diaries(id),
  CONSTRAINT weather_observations_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.work_diaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contract_id uuid NOT NULL,
  diary_date date NOT NULL,
  weather_conditions text CHECK (weather_conditions = ANY (ARRAY['Sunny'::text, 'Cloudy'::text, 'Rainy'::text, 'Heavy Rain'::text, 'Stormy'::text])),
  site_conditions text,
  work_progress text,
  manpower jsonb DEFAULT '[]'::jsonb,
  equipment jsonb DEFAULT '[]'::jsonb,
  materials_delivered jsonb DEFAULT '[]'::jsonb,
  issues_delays text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'acknowledged'::text])),
  created_by uuid NOT NULL,
  acknowledged_by uuid,
  acknowledged_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT work_diaries_pkey PRIMARY KEY (id),
  CONSTRAINT work_diaries_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id)
);